spring:
  datasource: 
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://localhost:3306/bootcamp_2512"
    username: "root"
    password: "admin1234"
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.MySQL8Dialect

# https://rt.data.gov.hk/v1/transport/mtr/getSchedule.php?line=TKL&sta=TKO

external-api:
  hk-mtr: 
    domain: "rt.data.gov.hk"
    mtr:
      path-segment: "v1/transport/mtr"
      path: "/getSchedule.php"
      