spring:
  datasource: 
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://localhost:3306/bootcamp_2512"
    username: "root"
    password: "admin1234"
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.MySQL8Dialect

external-api:
  hk-observatory: 
    domain: "data.weather.gov.hk"
    weather:
      path-segment: "weatherAPI/opendata"
      path: "/weather.php"
      dataset:
        nine-day: "fnd"